function BatteryEISandChargeComparator()
    % BatteryEISandChargeComparator - GUI for comparing EIS and charge data from multiple batteries
    %
    % Syntax: BatteryEISandChargeComparator()
    %
    % Opens an interactive GUI for loading and comparing multiple datasets
    
    % Create main figure
    fig = figure('Name', 'Battery EIS & Charge Comparator', ...
                 'NumberTitle', 'off', ...
                 'Position', [50, 50, 1500, 850], ...
                 'Color', [0.94 0.94 0.94], ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none');
    
    % Initialize data storage
    batteryData = struct();
    batteryData.datasets = [];
    batteryData.count = 0;
    setappdata(fig, 'batteryData', batteryData);
    setappdata(fig, 'currentBatteryIdx', []);
    setappdata(fig, 'comparisonMode', 'overlay');
    setappdata(fig, 'viewType', 'eis');  % 'eis' or 'charge'
    setappdata(fig, 'isUpdating', false);  % Add this line
    
    % Define color palette for different batteries
    colorPalette = {[0 0.447 0.741], [0.85 0.325 0.098], [0.466 0.674 0.188], ...
                    [0.494 0.184 0.556], [0.929 0.694 0.125], [0.301 0.745 0.933], ...
                    [0.635 0.078 0.184], [0.5 0.5 0.5]};
    setappdata(fig, 'colorPalette', colorPalette);
    
    % Create menu bar
    createMenuBar(fig);
    
    % Create main layout panels
    % Left panel for battery list and controls
    leftPanel = uipanel('Parent', fig, ...
                        'Position', [0.005 0.005 0.20 0.99], ...
                        'Title', 'Battery Datasets', ...
                        'FontSize', 11, ...
                        'FontWeight', 'bold', ...
                        'BackgroundColor', [0.96 0.96 0.96]);
    
    % Right panel for plots
    rightPanel = uipanel('Parent', fig, ...
                        'Position', [0.21 0.12 0.785 0.87], ...
                        'Title', 'Data Visualization', ...
                        'FontSize', 11, ...
                        'FontWeight', 'bold', ...
                        'BackgroundColor', 'white');
    
    % Bottom panel for controls
    bottomPanel = uipanel('Parent', fig, ...
                         'Position', [0.21 0.005 0.785 0.11], ...
                         'Title', 'Controls', ...
                         'FontSize', 10, ...
                         'BackgroundColor', [0.94 0.94 0.94]);
    
    % Create battery list in left panel
    uicontrol('Parent', leftPanel, ...
             'Style', 'text', ...
             'String', 'Loaded Batteries:', ...
             'Position', [10 750 180 20], ...
             'HorizontalAlignment', 'left', ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.96 0.96 0.96]);
    
    batteryListbox = uicontrol('Parent', leftPanel, ...
                               'Style', 'listbox', ...
                               'Position', [10 520 270 230], ...
                               'String', {}, ...
                               'Max', 10, ...  % Allow multiple selection
                               'Min', 0, ...
                               'Callback', @(src, evt) updateSelection(fig));
    
    % Add/Remove battery buttons
    addBtn = uicontrol('Parent', leftPanel, ...
                      'Style', 'pushbutton', ...
                      'String', '+ Add Battery', ...
                      'Position', [10 480 130 30], ...
                      'FontWeight', 'bold', ...
                      'ForegroundColor', [0 0.5 0], ...
                      'Callback', @(src, evt) addBattery(fig));
    
    removeBtn = uicontrol('Parent', leftPanel, ...
                         'Style', 'pushbutton', ...
                         'String', '- Remove', ...
                         'Position', [150 480 130 30], ...
                         'ForegroundColor', [0.7 0 0], ...
                         'Callback', @(src, evt) removeBattery(fig));
    
    % Battery info display
    uicontrol('Parent', leftPanel, ...
             'Style', 'text', ...
             'String', 'Battery Information:', ...
             'Position', [10 450 180 20], ...
             'HorizontalAlignment', 'left', ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.96 0.96 0.96]);
    
    infoText = uicontrol('Parent', leftPanel, ...
                        'Style', 'text', ...
                        'String', 'No battery loaded', ...
                        'Position', [10 280 270 160], ...
                        'HorizontalAlignment', 'left', ...
                        'BackgroundColor', 'white', ...
                        'FontSize', 9);
    
    % View Type Selection
    uicontrol('Parent', leftPanel, ...
             'Style', 'text', ...
             'String', 'View Type:', ...
             'Position', [10 245 180 20], ...
             'HorizontalAlignment', 'left', ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.96 0.96 0.96]);
    
    viewGroup = uibuttongroup('Parent', leftPanel, ...
                             'Position', [0.03 0.21 0.94 0.08], ...
                             'BackgroundColor', [0.96 0.96 0.96]);
    
    eisRadio = uicontrol('Parent', viewGroup, ...
                        'Style', 'radiobutton', ...
                        'String', 'EIS (Nyquist)', ...
                        'Position', [10 20 120 20], ...
                        'BackgroundColor', [0.96 0.96 0.96]);
    
    chargeRadio = uicontrol('Parent', viewGroup, ...
                           'Style', 'radiobutton', ...
                           'String', 'Charge Diagram', ...
                           'Position', [140 20 120 20], ...
                           'BackgroundColor', [0.96 0.96 0.96]);
    
    set(viewGroup, 'SelectionChangedFcn', @(src, evt) changeViewType(fig, evt));
    
    % Comparison mode panel
    uicontrol('Parent', leftPanel, ...
             'Style', 'text', ...
             'String', 'Comparison Mode:', ...
             'Position', [10 135 180 20], ...
             'HorizontalAlignment', 'left', ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.96 0.96 0.96]);
    
    modeGroup = uibuttongroup('Parent', leftPanel, ...
                             'Position', [0.03 0.08 0.94 0.08], ...
                             'BackgroundColor', [0.96 0.96 0.96]);
    
    overlayRadio = uicontrol('Parent', modeGroup, ...
                            'Style', 'radiobutton', ...
                            'String', 'Overlay', ...
                            'Position', [10 20 120 20], ...
                            'BackgroundColor', [0.96 0.96 0.96]);
    
    sideBySideRadio = uicontrol('Parent', modeGroup, ...
                                'Style', 'radiobutton', ...
                                'String', 'Side-by-Side', ...
                                'Position', [140 20 120 20], ...
                                'BackgroundColor', [0.96 0.96 0.96]);
    
    set(modeGroup, 'SelectionChangedFcn', @(src, evt) changeComparisonMode(fig, evt));
    
    % Export button
    exportCompBtn = uicontrol('Parent', leftPanel, ...
                             'Style', 'pushbutton', ...
                             'String', 'Export Comparison', ...
                             'Position', [10 20 270 30], ...
                             'FontWeight', 'bold', ...
                             'Callback', @(src, evt) exportCurrentView(fig));
    
    % Create axes in right panel
    createPlotAxes(rightPanel, fig);
    
    % Create controls in bottom panel
    createBottomControls(bottomPanel, fig);
    
    % Store UI handles
    handles = struct('batteryListbox', batteryListbox, ...
                    'infoText', infoText, ...
                    'addBtn', addBtn, ...
                    'removeBtn', removeBtn, ...
                    'leftPanel', leftPanel, ...
                    'rightPanel', rightPanel, ...
                    'bottomPanel', bottomPanel, ...
                    'modeGroup', modeGroup, ...
                    'viewGroup', viewGroup, ...
                    'exportCompBtn', exportCompBtn);
    setappdata(fig, 'handles', handles);
end













