function createMenuBar(fig)
    % Create menu bar with file operations
    
    fileMenu = uimenu(fig, 'Text', 'File');
    uimenu(fileMenu, 'Text', 'Add Battery Dataset...', ...
           'Accelerator', 'O', ...
           'MenuSelectedFcn', @(src, evt) addBaseline(fig));
    uimenu(fileMenu, 'Text', 'Batch Import...', ...
           'MenuSelectedFcn', @(src, evt) batchImport(fig));
    uimenu(fileMenu, 'Text', 'Export View...', ...
           'Accelerator', 'S', ...
           'MenuSelectedFcn', @(src, evt) exportCurrentView(fig));
    uimenu(fileMenu, 'Text', 'Clear All', ...
           'Separator', 'on', ...
           'MenuSelectedFcn', @(src, evt) clearAll(fig));
    
    analysisMenu = uimenu(fig, 'Text', 'Analysis');
    uimenu(analysisMenu, 'Text', 'EIS Grid (All SOC Levels)', ...
           'Accelerator', 'G', ...
           'MenuSelectedFcn', @(src, evt) launchEISGrid(fig));
    uimenu(analysisMenu, 'Text', 'Compare at Fixed SOC...', ...
           'MenuSelectedFcn', @(src, evt) compareAtFixedSOC(fig));
    uimenu(analysisMenu, 'Text', 'Generate Report...', ...
           'MenuSelectedFcn', @(src, evt) generateReport(fig));
end

function launchEISGrid(fig)
    % Launch EIS Grid view for selected batteries
    batteryData = getappdata(fig, 'batteryData');
    currentIdx = getappdata(fig, 'currentBatteryIdx');

    if isempty(currentIdx) || batteryData.count == 0
        msgbox('Please load and select at least one battery dataset first.', ...
               'No Data Selected', 'warn');
        return;
    end

    plotEISGrid(batteryData, currentIdx);
end