function createBottomControls(panel, fig)
    % Create control elements in bottom panel
    
    % SOC slider (for EIS view)
    socLabel = uicontrol('Parent', panel, ...
                        'Style', 'text', ...
                        'String', 'SOC:', ...
                        'Position', [20 50 40 20], ...
                        'BackgroundColor', [0.94 0.94 0.94], ...
                        'HorizontalAlignment', 'right');
    
    socSlider = uicontrol('Parent', panel, ...
                         'Style', 'slider', ...
                         'Position', [70 50 400 20], ...
                         'Min', 0, ...
                         'Max', 180, ...
                         'Value', 50, ...
                         'Enable', 'off');
    
    % Add listener for continuous slider updates
    hSliderListener = addlistener(socSlider, 'Value', 'PostSet', ...
                                  @(src, evt) continuousSliderUpdate(fig));
    setappdata(fig, 'sliderListener', hSliderListener);
    
    % Rest of the controls remain the same...
    socDisplay = uicontrol('Parent', panel, ...
                          'Style', 'text', ...
                          'String', '50.0%', ...
                          'Position', [480 50 60 20], ...
                          'BackgroundColor', 'white', ...
                          'FontWeight', 'bold');
    
    % Navigation buttons
    prevBtn = uicontrol('Parent', panel, ...
                       'Style', 'pushbutton', ...
                       'String', '◄', ...
                       'Position', [550 47 30 25], ...
                       'Enable', 'off', ...
                       'Callback', @(src, evt) navigateSOCComparator(fig, -1));
    
    nextBtn = uicontrol('Parent', panel, ...
                       'Style', 'pushbutton', ...
                       'String', '►', ...
                       'Position', [585 47 30 25], ...
                       'Enable', 'off', ...
                       'Callback', @(src, evt) navigateSOCComparator(fig, 1));
    
    % Display options
    showMarkersCheck = uicontrol('Parent', panel, ...
                                'Style', 'checkbox', ...
                                'String', 'Frequency Markers', ...
                                'Position', [630 50 130 20], ...
                                'BackgroundColor', [0.94 0.94 0.94], ...
                                'Value', 0, ...
                                'Callback', @(src, evt) updatePlotsComparator(fig));
    
    showLegendCheck = uicontrol('Parent', panel, ...
                               'Style', 'checkbox', ...
                               'String', 'Show Legend', ...
                               'Position', [770 50 100 20], ...
                               'BackgroundColor', [0.94 0.94 0.94], ...
                               'Value', 1, ...
                               'Callback', @(src, evt) updatePlotsComparator(fig));
    
    gridCheck = uicontrol('Parent', panel, ...
                         'Style', 'checkbox', ...
                         'String', 'Grid', ...
                         'Position', [880 50 60 20], ...
                         'BackgroundColor', [0.94 0.94 0.94], ...
                         'Value', 1, ...
                         'Callback', @(src, evt) updatePlotsComparator(fig));
    
    % SOC marker for charge view (initially hidden)
    socMarkerCheck = uicontrol('Parent', panel, ...
                              'Style', 'checkbox', ...
                              'String', 'Show SOC Marker', ...
                              'Position', [630 50 130 20], ...
                              'BackgroundColor', [0.94 0.94 0.94], ...
                              'Value', 1, ...
                              'Visible', 'off', ...
                              'Callback', @(src, evt) updatePlotsComparator(fig));
    
    % Export button
    exportBtn = uicontrol('Parent', panel, ...
                         'Style', 'pushbutton', ...
                         'String', 'Export View', ...
                         'Position', [1000 45 100 30], ...
                         'Callback', @(src, evt) exportCurrentView(fig));
    
    % Info display
    statusText = uicontrol('Parent', panel, ...
                          'Style', 'text', ...
                          'String', 'Ready', ...
                          'Position', [20 10 1080 25], ...
                          'BackgroundColor', [0.94 0.94 0.94], ...
                          'HorizontalAlignment', 'left', ...
                          'FontSize', 9);
    
    % Store control handles
    controls = struct('socSlider', socSlider, ...
                     'socDisplay', socDisplay, ...
                     'socLabel', socLabel, ...
                     'prevBtn', prevBtn, ...
                     'nextBtn', nextBtn, ...
                     'showMarkersCheck', showMarkersCheck, ...
                     'showLegendCheck', showLegendCheck, ...
                     'gridCheck', gridCheck, ...
                     'socMarkerCheck', socMarkerCheck, ...
                     'exportBtn', exportBtn, ...
                     'statusText', statusText);
    setappdata(fig, 'controls', controls);
end