function EISVisualizer(SOCEIScan)
    % EISVisualizer - Interactive visualization tool for EIS data across SOC levels
    %
    % Syntax: EISVisualizer(SOCEIScan)
    %
    % Input:
    %   SOCEIScan - Structure from EISSOCScanReader containing EIS scans
    
    % Validate input
    if ~isstruct(SOCEIScan) || ~isfield(SOCEIScan, 'Scans')
        error('Input must be a valid SOCEIScan structure from EISSOCScanReader');
    end
    
    % Get valid scans only
    validIdx = find(SOCEIScan.ValidScans);
    if isempty(validIdx)
        error('No valid EIS scans found in the data');
    end
    
    % Calculate global axis limits for all data
    [xlimits, ylimits] = calculateGlobalLimits(SOCEIScan, validIdx);
    
    % Create figure
    fig = figure('Name', 'EIS Data Visualizer - Nyquist Plot', ...
                 'NumberTitle', 'off', ...
                 'Position', [100, 100, 900, 700], ...
                 'Color', [0.94 0.94 0.94]);
    
    % Store data in figure
    setappdata(fig, 'SOCEIScan', SOCEIScan);
    setappdata(fig, 'validIdx', validIdx);
    setappdata(fig, 'currentIdx', 1);
    setappdata(fig, 'xlimits', xlimits);
    setappdata(fig, 'ylimits', ylimits);
    
    % Create main panel for plot
    mainPanel = uipanel('Parent', fig, ...
                        'Position', [0.01 0.15 0.98 0.84], ...
                        'BackgroundColor', 'white');
    
    % Create control panel
    controlPanel = uipanel('Parent', fig, ...
                          'Position', [0.01 0.01 0.98 0.13], ...
                          'BackgroundColor', [0.94 0.94 0.94]);
    
    % Create Nyquist plot axis (larger now since it's the only plot)
    ax = axes('Parent', mainPanel, ...
              'Position', [0.08 0.1 0.87 0.85], ...
              'Box', 'on');
    title(ax, 'Nyquist Plot', 'FontSize', 14, 'FontWeight', 'bold');
    xlabel(ax, 'Z_{real} (\Omega)', 'FontSize', 12);
    ylabel(ax, '-Z_{imag} (\Omega)', 'FontSize', 12);
    grid(ax, 'on');
    set(ax, 'GridLineStyle', ':');
    
    % Set fixed limits
    xlim(ax, xlimits);
    ylim(ax, ylimits);
    
    % Store axis handle
    setappdata(fig, 'mainAxis', ax);
    
    % Create slider
    sliderLabel = uicontrol('Parent', controlPanel, ...
                            'Style', 'text', ...
                            'String', 'SOC:', ...
                            'Position', [20 50 40 20], ...
                            'BackgroundColor', [0.94 0.94 0.94], ...
                            'HorizontalAlignment', 'right', ...
                            'FontSize', 10);
    
    slider = uicontrol('Parent', controlPanel, ...
                       'Style', 'slider', ...
                       'Position', [70 50 400 20], ...
                       'Min', 1, ...
                       'Max', length(validIdx), ...
                       'Value', 1, ...
                       'SliderStep', [1/(length(validIdx)-1), 0.1]);
    
    % SOC value display
    socDisplay = uicontrol('Parent', controlPanel, ...
                          'Style', 'text', ...
                          'String', '', ...
                          'Position', [480 50 80 20], ...
                          'BackgroundColor', 'white', ...
                          'FontWeight', 'bold', ...
                          'FontSize', 11, ...
                          'HorizontalAlignment', 'center');
    
    % Info text
    infoText = uicontrol('Parent', controlPanel, ...
                         'Style', 'text', ...
                         'String', '', ...
                         'Position', [70 15 700 25], ...
                         'BackgroundColor', [0.94 0.94 0.94], ...
                         'HorizontalAlignment', 'left', ...
                         'FontSize', 9);
    
    % Navigation buttons
    prevBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '-', ...
                        'Position', [570 47 30 25], ...
                        'FontSize', 10, ...
                        'Callback', @(src, evt) navigateSOC(fig, -1));
    
    nextBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '+', ...
                        'Position', [605 47 30 25], ...
                        'FontSize', 10, ...
                        'Callback', @(src, evt) navigateSOC(fig, 1));
    
    % Compare mode checkbox
    compareCheck = uicontrol('Parent', controlPanel, ...
                             'Style', 'checkbox', ...
                             'String', 'Compare Mode', ...
                             'Position', [650 50 100 20], ...
                             'BackgroundColor', [0.94 0.94 0.94], ...
                             'Value', 0, ...
                             'FontSize', 9);
    
    % Clear comparison button
    clearBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', 'Clear', ...
                        'Position', [755 47 50 25], ...
                        'Enable', 'off', ...
                        'FontSize', 9, ...
                        'Callback', @(src, evt) clearComparison(fig));
    
    % Frequency marker checkbox
    freqCheck = uicontrol('Parent', controlPanel, ...
                         'Style', 'checkbox', ...
                         'String', 'Freq. Markers', ...
                         'Position', [815 50 100 20], ...
                         'BackgroundColor', [0.94 0.94 0.94], ...
                         'Value', 0, ...
                         'FontSize', 9);
    
    % Store UI handles
    handles = struct('slider', slider, ...
                    'socDisplay', socDisplay, ...
                    'infoText', infoText, ...
                    'prevBtn', prevBtn, ...
                    'nextBtn', nextBtn, ...
                    'compareCheck', compareCheck, ...
                    'clearBtn', clearBtn, ...
                    'freqCheck', freqCheck);
    setappdata(fig, 'handles', handles);
    
    % Set callbacks
    set(slider, 'Callback', @(src, evt) updatePlot(fig));
    set(compareCheck, 'Callback', @(src, evt) toggleCompareMode(fig));
    set(freqCheck, 'Callback', @(src, evt) updatePlot(fig));
    
    % Initialize comparison data storage
    setappdata(fig, 'comparisonData', []);
    
    % Initial plot
    updatePlot(fig);
end