function EISVisualizerWithCharge(SOCEIScan, chargeData)
    % EISVisualizerWithCharge - Interactive visualization of EIS and charge data
    %
    % Syntax: EISVisualizerWithCharge(SOCEIScan, chargeData)
    %
    % Inputs:
    %   SOCEIScan - Structure from EISSOCScanReader containing EIS scans
    %   chargeData - Structure from chargeDataReader (optional)
    
    % Handle optional charge data
    if nargin < 2
        chargeData = [];
    end
    
    % Validate input
    if ~isstruct(SOCEIScan) || ~isfield(SOCEIScan, 'Scans')
        error('Input must be a valid SOCEIScan structure from EISSOCScanReader');
    end
    
    % Get valid scans only
    validIdx = find(SOCEIScan.ValidScans);
    if isempty(validIdx)
        error('No valid EIS scans found in the data');
    end
    
    % Calculate global axis limits for Nyquist plot
    [xlimits, ylimits] = calculateGlobalLimits(SOCEIScan, validIdx);
    
    % Create figure
    if ~isempty(chargeData)
        figWidth = 1400;
        figTitle = 'EIS & Charge Data Visualizer';
    else
        figWidth = 900;
        figTitle = 'EIS Data Visualizer';
    end
    
    fig = figure('Name', figTitle, ...
                 'NumberTitle', 'off', ...
                 'Position', [50, 100, figWidth, 700], ...
                 'Color', [0.94 0.94 0.94]);
    
    % Store data in figure
    setappdata(fig, 'SOCEIScan', SOCEIScan);
    setappdata(fig, 'chargeData', chargeData);
    setappdata(fig, 'validIdx', validIdx);
    setappdata(fig, 'currentIdx', 1);
    setappdata(fig, 'xlimits', xlimits);
    setappdata(fig, 'ylimits', ylimits);
    
    % Create main panel for plots
    mainPanel = uipanel('Parent', fig, ...
                        'Position', [0.01 0.15 0.98 0.84], ...
                        'BackgroundColor', 'white');
    
    % Create control panel
    controlPanel = uipanel('Parent', fig, ...
                          'Position', [0.01 0.01 0.98 0.13], ...
                          'BackgroundColor', [0.94 0.94 0.94]);
    
    % Create axes based on available data
    if ~isempty(chargeData)
        % Create Nyquist plot axis (left)
        ax1 = axes('Parent', mainPanel, ...
                   'Position', [0.05 0.1 0.42 0.85], ...
                   'Box', 'on');
        title(ax1, 'Nyquist Plot', 'FontSize', 14, 'FontWeight', 'bold');
        xlabel(ax1, 'Z_{real} (\Omega)', 'FontSize', 12);
        ylabel(ax1, '-Z_{imag} (\Omega)', 'FontSize', 12);
        grid(ax1, 'on');
        set(ax1, 'GridLineStyle', ':');
        xlim(ax1, xlimits);
        ylim(ax1, ylimits);
        
        % Create charge diagram axis with dual y-axes (right)
        ax2 = axes('Parent', mainPanel, ...
                   'Position', [0.53 0.1 0.42 0.85], ...
                   'Box', 'on');
        title(ax2, 'Charge Diagram', 'FontSize', 14, 'FontWeight', 'bold');
        xlabel(ax2, 'SOC (%)', 'FontSize', 12);
        ylabel(ax2, 'Voltage (V)', 'FontSize', 12, 'Color', [0 0 0.8]);
        set(ax2, 'YColor', [0 0 0.8]);
        grid(ax2, 'on');
        set(ax2, 'GridLineStyle', ':');
        
        % Plot voltage curve
        hold(ax2, 'on');
        plot(ax2, chargeData.SOC_Percent, chargeData.Voltage_V, 'b-', ...
             'LineWidth', 2);
        xlim(ax2, [0 max(100, max(chargeData.SOC_Percent))]);
        
        % Create second y-axis for current
        ax3 = axes('Parent', mainPanel, ...
                   'Position', ax2.Position, ...
                   'Color', 'none', ...
                   'XAxisLocation', 'bottom', ...
                   'YAxisLocation', 'right', ...
                   'Box', 'off');
        ylabel(ax3, 'Current (A)', 'FontSize', 12, 'Color', [0.8 0 0]);
        set(ax3, 'YColor', [0.8 0 0]);
        set(ax3, 'XTick', []);
        set(ax3, 'XColor', 'none');
        
        % Plot current curve
        hold(ax3, 'on');
        plot(ax3, chargeData.SOC_Percent, chargeData.Current_A, 'r-', ...
             'LineWidth', 2, 'LineStyle', '--');
        xlim(ax3, [0 max(100, max(chargeData.SOC_Percent))]);
        
        % Add legend
        legend(ax2, {'Voltage'}, 'Location', 'northwest', 'FontSize', 9);
        legend(ax3, {'Current'}, 'Location', 'northeast', 'FontSize', 9);
        
        % Store all axes
        setappdata(fig, 'axes', [ax1, ax2, ax3]);
    else
        % Single Nyquist plot
        ax1 = axes('Parent', mainPanel, ...
                   'Position', [0.08 0.1 0.87 0.85], ...
                   'Box', 'on');
        title(ax1, 'Nyquist Plot', 'FontSize', 14, 'FontWeight', 'bold');
        xlabel(ax1, 'Z_{real} (\Omega)', 'FontSize', 12);
        ylabel(ax1, '-Z_{imag} (\Omega)', 'FontSize', 12);
        grid(ax1, 'on');
        set(ax1, 'GridLineStyle', ':');
        xlim(ax1, xlimits);
        ylim(ax1, ylimits);
        
        setappdata(fig, 'axes', ax1);
    end
    
    % Create slider
    sliderLabel = uicontrol('Parent', controlPanel, ...
                            'Style', 'text', ...
                            'String', 'SOC:', ...
                            'Position', [20 50 40 20], ...
                            'BackgroundColor', [0.94 0.94 0.94], ...
                            'HorizontalAlignment', 'right', ...
                            'FontSize', 10);
    
    slider = uicontrol('Parent', controlPanel, ...
                       'Style', 'slider', ...
                       'Position', [70 50 400 20], ...
                       'Min', 1, ...
                       'Max', length(validIdx), ...
                       'Value', 1, ...
                       'SliderStep', [1/(length(validIdx)-1), 0.1]);
    
    % SOC value display
    socDisplay = uicontrol('Parent', controlPanel, ...
                          'Style', 'text', ...
                          'String', '', ...
                          'Position', [480 50 80 20], ...
                          'BackgroundColor', 'white', ...
                          'FontWeight', 'bold', ...
                          'FontSize', 11, ...
                          'HorizontalAlignment', 'center');
    
    % Info text
    infoTextWidth = ~isempty(chargeData) * 200 + 700;
    infoText = uicontrol('Parent', controlPanel, ...
                         'Style', 'text', ...
                         'String', '', ...
                         'Position', [70 15 infoTextWidth 25], ...
                         'BackgroundColor', [0.94 0.94 0.94], ...
                         'HorizontalAlignment', 'left', ...
                         'FontSize', 9);
    
    % Navigation buttons
    prevBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '?', ...
                        'Position', [570 47 30 25], ...
                        'FontSize', 10, ...
                        'Callback', @(src, evt) navigateSOC(fig, -1));
    
    nextBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '?', ...
                        'Position', [605 47 30 25], ...
                        'FontSize', 10, ...
                        'Callback', @(src, evt) navigateSOC(fig, 1));
    
    % Compare mode checkbox
    compareCheck = uicontrol('Parent', controlPanel, ...
                             'Style', 'checkbox', ...
                             'String', 'Compare Mode', ...
                             'Position', [650 50 100 20], ...
                             'BackgroundColor', [0.94 0.94 0.94], ...
                             'Value', 0, ...
                             'FontSize', 9);
    
    % Clear comparison button
    clearBtn = uicontrol('Parent', controlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', 'Clear', ...
                        'Position', [755 47 50 25], ...
                        'Enable', 'off', ...
                        'FontSize', 9, ...
                        'Callback', @(src, evt) clearComparison(fig));
    
    % Frequency marker checkbox
    freqCheck = uicontrol('Parent', controlPanel, ...
                         'Style', 'checkbox', ...
                         'String', 'Freq. Markers', ...
                         'Position', [815 50 100 20], ...
                         'BackgroundColor', [0.94 0.94 0.94], ...
                         'Value', 0, ...
                         'FontSize', 9);
    
    % Store UI handles
    handles = struct('slider', slider, ...
                    'socDisplay', socDisplay, ...
                    'infoText', infoText, ...
                    'prevBtn', prevBtn, ...
                    'nextBtn', nextBtn, ...
                    'compareCheck', compareCheck, ...
                    'clearBtn', clearBtn, ...
                    'freqCheck', freqCheck);
    setappdata(fig, 'handles', handles);
    
    % Set callbacks
    set(slider, 'Callback', @(src, evt) updatePlots(fig));
    set(compareCheck, 'Callback', @(src, evt) toggleCompareMode(fig));
    set(freqCheck, 'Callback', @(src, evt) updatePlots(fig));
    
    % Initialize comparison data storage
    setappdata(fig, 'comparisonData', []);
    setappdata(fig, 'socMarkers', []);
    
    % Initial plot
    updatePlots(fig);
end